// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrtqbq-3Qbe3r8_jTsP-0dsMqXKO8dHBk',
    appId: '1:155501649875:web:016a4ae11351b752bb9926',
    messagingSenderId: '155501649875',
    projectId: 'portfolio-e0229',
    authDomain: 'portfolio-e0229.firebaseapp.com',
    storageBucket: 'portfolio-e0229.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCX9ZyYFVM0t_ENHLKmTtgOkHQKbwoSuEw',
    appId: '1:155501649875:android:ab9c93f3ffb1afa8bb9926',
    messagingSenderId: '155501649875',
    projectId: 'portfolio-e0229',
    storageBucket: 'portfolio-e0229.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIlLtMeniKeUzmY5Xrh5SPNMu9GQijyss',
    appId: '1:155501649875:ios:7a1c9e70726ee00dbb9926',
    messagingSenderId: '155501649875',
    projectId: 'portfolio-e0229',
    storageBucket: 'portfolio-e0229.firebasestorage.app',
    iosBundleId: 'com.example.portfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIlLtMeniKeUzmY5Xrh5SPNMu9GQijyss',
    appId: '1:155501649875:ios:7a1c9e70726ee00dbb9926',
    messagingSenderId: '155501649875',
    projectId: 'portfolio-e0229',
    storageBucket: 'portfolio-e0229.firebasestorage.app',
    iosBundleId: 'com.example.portfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrtqbq-3Qbe3r8_jTsP-0dsMqXKO8dHBk',
    appId: '1:155501649875:web:619ad7c1b1d896febb9926',
    messagingSenderId: '155501649875',
    projectId: 'portfolio-e0229',
    authDomain: 'portfolio-e0229.firebaseapp.com',
    storageBucket: 'portfolio-e0229.firebasestorage.app',
  );
}
